%YAML:1.0 # need to specify the file type at the top!

imu:
  accel_noise: 0.1155  # [ m / s^2 / sqrt(Hz) ]   ( accel "white noise" )
  accel_bias: 0.00726   # [ m / s^3 / sqrt(Hz) ].  ( accel bias diffusion )
  gyro_noise: 0.004815   # [ rad / s / sqrt(Hz) ]   ( gyro "white noise" )
  gyro_bias: 4.26e-04    # [ rad / s^2 / sqrt(Hz) ] ( gyro bias diffusion )
  topic: "/imu/data_raw"
